pipelines:
  Application:
    group: Development

    materials:
      mygit:
        git: /vagrant/2016-workshop
    stages:
      - build:
          jobs:
            build:
              tasks:
                - rake:
                    target: build
      - unit_test:
          jobs:
            build:
              tasks:
                - rake:
                    target: unit_test
      - package:
          jobs:
            build:
              tasks:
                - rake:
                    target: package
                    