pipelines:
  Application:
    group: Development

    materials:
      mygit:
        git: /vagrant/2016-workshop
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: rake
                    arguments: build
      - unit_test:
          jobs:
            build:
              tasks:
                - exec:
                    command: rake
                    arguments: unit_test
      - package:
          jobs:
            build:
              tasks:
                - exec:
                    command: rake
                    arguments: package
                    