pipelines:  
  FunctionalTesting:
    group: Development
    locking: on

    materials:
      services:
        pipeline: Application
        stage: package

    stages:
      - DeployApplications:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: echo
      - FunctionalTests:
          jobs:
            runTests:
              runinstances: 3
              tasks:
                - exec:
                    command: echo

  UserAcceptance:
    group: Development
    locking: on

    materials:
      services:
        pipeline: Application
        stage: package

    stages:
      - DeployApplications:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: echo
      - Approved:
          approval:
            type: success
          jobs:
            approve:
              tasks:
                - exec:
                    command: echo

