pipelines:
  SecurityTests:
    group: Operations

    materials:
      SecurityGit:
        git: /vagrant/2016-workshop-security
      services:
        pipeline: Application
        stage: package
    stages:
      - TestSecurity:
          jobs:
            test_security:
              tasks:
                - exec:
                    command: rake
                    arguments:
                      - test_security
                    