pipelines:
  Staging:
    group: Operations

    materials:
      uat: 
        pipeline: UserAcceptance
        stage: Approved
      functional_testing:
        pipeline: FunctionalTesting
        stage: FunctionalTests

    stages:
      - DeployApplications:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: echo
      - VerifyDeployment:
          jobs:
            verify:
              tasks:
                - exec:
                    command: echo


  Production:
    group: Operations

    materials:
      uat: 
        pipeline: Staging
        stage: VerifyDeployment

    stages:
      - DeployApplications:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: echo
      - VerifyDeployment:
          jobs:
            verify:
              tasks:
                - exec:
                    command: echo