pipelines:
  Staging:
    group: Operations

    materials:
      uat: 
        pipeline: FunctionalTesting
        stage: Approved

    stages:
      - DeployApplications:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: echo