pipelines:
  Application:
    group: Development

    materials:
      mygit:
        git: https://github.com/kmugrage/webinar-code.git

    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo
      - unit_test:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo
      - package:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo

  Functional_Testing:
    group: Development

      materials:
        upstream:
          pipeline: Application
          stage: package

      stages:
        - install_packages:
            jobs:
              build:
                tasks:
                - exec:
                    command: echo
                    