pipelines:
  Application:
    group: Development

    materials:
      mygit:
        git: https://github.com/kmugrage/webinar-code.git

    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo
      - unit_test:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo
      - package:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo

  FunctionalTesting:
    group: Development

    materials:
      services:
        pipeline: Application
        stage: package

    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo 
